### ISSUE TITLE
Find SDL2.cmake sets SDL2_INCLUDE_DIR incorrectly

### ISSUE THREAD

**Issue by ghost** [bcmpinc/voxel-engine#1]
## System config

System: Mac OSX 10.9
/Libraries/Frameworks contains SDL.framework as well as SDL2.framework
## The FindSDL2.cmake sets 

SDL2_INCLUDE_DIR to /Library/Frameworks/SDL.framework/headers (incorrectly)
SLD2_LIBRARY to /Library/Frameworks/SDL2.framework;-framework Cocoa (correct)

**Comment by bcmpinc** [comment]
For the include dir I checked for SDL.h rather than for some SDL2 specific header, such as SDL_assert.h. Commit 56488848e25dc5913bc279d462a5c3c1b621cb45 should fix this issue.
